-- CreateTable
CREATE TABLE `MENSAGENS` (
    `MEN_ID` INTEGER NOT NULL,
    `MEN_MENSAGEM` VARCHAR(200) NOT NULL,
    `MEN_DATA` DATETIME(3) NOT NULL,
    `FK_TOPICO_TOP_ID` INTEGER NOT NULL,
    `FK_USUARIOS_USR_ID` INTEGER NOT NULL,

    PRIMARY KEY (`MEN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MENSAGENS` ADD CONSTRAINT `MENSAGENS_FK_TOPICO_TOP_ID_fkey` FOREIGN KEY (`FK_TOPICO_TOP_ID`) REFERENCES `TOPICOS`(`TOP_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENSAGENS` ADD CONSTRAINT `MENSAGENS_FK_USUARIOS_USR_ID_fkey` FOREIGN KEY (`FK_USUARIOS_USR_ID`) REFERENCES `USUARIOS`(`USR_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
